FTMSG/1.0
Content-Type: application/json
Message-Id: 0205c4dd-5430-33ac-bb1f-fbfc347b1475
Message-Timestamp: 2016-07-19T10:23:38.688Z
Message-Type: alphaville-series
Origin-System-Id: http://cmdb.ft.com/systems/upp
X-Request-Id: tid_VJWszPgsMN

{"uuid":"0205c4dd-5430-33ac-bb1f-fbfc347b1475","alternativeIdentifiers":{"TME":["ODQ1ZGM3ZDctYWU4OS00ZmVkLWE4MTktOWVkY2JiM2ZlNTA3-dG9waWNz"],"uuids":["0205c4dd-5430-33ac-bb1f-fbfc347b1475"]},"prefLabel":"3D printing","type":"AlphavilleSeries"}
